[package]
name = "frontbox-pin2dmd"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
frontbox = { path = "../frontbox" }
frontbox-canvas = { path = "../frontbox-canvas" }
frontbox-sound = { path = "../frontbox-sound", optional = true }
rusb = "0.9.4"
image = "0.25.9"
rand = "0.10.0"
serde = "1.0.229"
serde_json = "1.0.151"

[features]
default = ["sound"]
sound = ["dep:frontbox-sound"]
