[package]
name = "frontbox-turn-based"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
frontbox = { path = "../frontbox" }
tokio = { version = "1", features = ["full"] }
dyn-clone = "1.0.20"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.5"
